"""Child element order of the AUTOSAR system-template elements the gateway generator writes.

AUTOSAR XML is validated against an XSD whose content models are sequences, so a child must be
inserted at its schema position. The table below was derived from the AUTOSAR R21-11 schema; the
relative order of these elements is the same in every R4.x schema up to R24-11. List containers
(e.g. ELEMENTS, PDU-TRIGGERINGS) are not in the table: their children may appear in any order.
"""
from __future__ import annotations

import uuid

from .. import arxml
from ..arxml import local, q

_ORDERS = (
    ('AUTOSAR',
     'FILE-INFO-COMMENT ADMIN-DATA INTRODUCTION AR-PACKAGES'),
    ('AR-PACKAGE',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'BLUEPRINT-POLICYS SHORT-NAME-PATTERN REFERENCE-BASES ELEMENTS AR-PACKAGES VARIATION-POINT'),
    ('CAN-CLUSTER',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'VARIATION-POINT CAN-CLUSTER-VARIANTS'),
    ('CAN-CLUSTER-CONDITIONAL',
     'BAUDRATE PHYSICAL-CHANNELS PROTOCOL-NAME PROTOCOL-VERSION SPEED BUS-OFF-RECOVERY CAN-FD-BAUDRATE '
     'VARIATION-POINT'),
    ('CAN-PHYSICAL-CHANNEL',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'COMM-CONNECTORS FRAME-TRIGGERINGS I-SIGNAL-TRIGGERINGS MANAGED-PHYSICAL-CHANNEL-REFS PDU-TRIGGERINGS '
     'VARIATION-POINT'),
    ('COMMUNICATION-CONNECTOR-REF-CONDITIONAL',
     'COMMUNICATION-CONNECTOR-REF VARIATION-POINT'),
    ('CAN-FRAME-TRIGGERING',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'FRAME-PORT-REFS FRAME-REF PDU-TRIGGERINGS VARIATION-POINT ABSOLUTELY-SCHEDULED-TIMINGS '
     'CAN-ADDRESSING-MODE CAN-FD-FRAME-SUPPORT CAN-FRAME-RX-BEHAVIOR CAN-FRAME-TX-BEHAVIOR IDENTIFIER '
     'J-1939-REQUESTABLE RX-IDENTIFIER-RANGE RX-MASK TX-MASK'),
    ('PDU-TRIGGERING-REF-CONDITIONAL',
     'PDU-TRIGGERING-REF VARIATION-POINT'),
    ('PDU-TRIGGERING',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'I-PDU-PORT-REFS I-PDU-REF I-SIGNAL-TRIGGERINGS SEC-OC-CRYPTO-MAPPING-REF '
     'TRIGGER-I-PDU-SEND-CONDITIONS VARIATION-POINT'),
    ('I-SIGNAL-TRIGGERING-REF-CONDITIONAL',
     'I-SIGNAL-TRIGGERING-REF VARIATION-POINT'),
    ('I-SIGNAL-TRIGGERING',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'I-SIGNAL-GROUP-REF I-SIGNAL-PORT-REFS I-SIGNAL-REF VARIATION-POINT'),
    ('CAN-FRAME',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'VARIATION-POINT FRAME-LENGTH PDU-TO-FRAME-MAPPINGS'),
    ('PDU-TO-FRAME-MAPPING',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'PACKING-BYTE-ORDER PDU-REF START-POSITION UPDATE-INDICATION-BIT-POSITION VARIATION-POINT'),
    ('I-SIGNAL-I-PDU',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'VARIATION-POINT HAS-DYNAMIC-LENGTH LENGTH META-DATA-LENGTH CONTAINED-I-PDU-PROPS '
     'I-PDU-TIMING-SPECIFICATIONS I-SIGNAL-TO-PDU-MAPPINGS PDU-COUNTERS PDU-REPLICATIONS '
     'UNUSED-BIT-PATTERN'),
    ('I-PDU-TIMING',
     'DESC CATEGORY INTRODUCTION ADMIN-DATA MINIMUM-DELAY TRANSMISSION-MODE-DECLARATION VARIATION-POINT'),
    ('TRANSMISSION-MODE-DECLARATION',
     'MODE-DRIVEN-FALSE-CONDITIONS MODE-DRIVEN-TRUE-CONDITIONS TRANSMISSION-MODE-CONDITIONS '
     'TRANSMISSION-MODE-FALSE-TIMING TRANSMISSION-MODE-TRUE-TIMING'),
    ('TRANSMISSION-MODE-CONDITION',
     'DATA-FILTER I-SIGNAL-IN-I-PDU-REF'),
    ('DATA-FILTER',
     'DATA-FILTER-TYPE MASK MAX MIN OFFSET PERIOD X'),
    ('TRANSMISSION-MODE-TRUE-TIMING',
     'CYCLIC-TIMING EVENT-CONTROLLED-TIMING'),
    ('EVENT-CONTROLLED-TIMING',
     'DESC CATEGORY INTRODUCTION ADMIN-DATA NUMBER-OF-REPETITIONS REPETITION-PERIOD'),
    ('CYCLIC-TIMING',
     'DESC CATEGORY INTRODUCTION ADMIN-DATA TIME-OFFSET TIME-PERIOD'),
    ('TIME-PERIOD',
     'TOLERANCE VALUE'),
    ('I-SIGNAL-TO-I-PDU-MAPPING',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'I-SIGNAL-GROUP-REF I-SIGNAL-REF PACKING-BYTE-ORDER START-POSITION TRANSFER-PROPERTY '
     'UPDATE-INDICATION-BIT-POSITION VARIATION-POINT'),
    ('I-SIGNAL',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'VARIATION-POINT DATA-TRANSFORMATIONS DATA-TYPE-POLICY I-SIGNAL-PROPS I-SIGNAL-TYPE INIT-VALUE LENGTH '
     'NETWORK-REPRESENTATION-PROPS SYSTEM-SIGNAL-REF TIMEOUT-SUBSTITUTION-VALUE '
     'TRANSFORMATION-I-SIGNAL-PROPSS'),
    ('INIT-VALUE',
     'APPLICATION-ASSOC-MAP-VALUE-SPECIFICATION APPLICATION-RULE-BASED-VALUE-SPECIFICATION '
     'APPLICATION-VALUE-SPECIFICATION ARRAY-VALUE-SPECIFICATION COMPOSITE-RULE-BASED-VALUE-SPECIFICATION '
     'CONSTANT-REFERENCE NOT-AVAILABLE-VALUE-SPECIFICATION NUMERICAL-RULE-BASED-VALUE-SPECIFICATION '
     'NUMERICAL-VALUE-SPECIFICATION RECORD-VALUE-SPECIFICATION REFERENCE-VALUE-SPECIFICATION '
     'TEXT-VALUE-SPECIFICATION'),
    ('NUMERICAL-VALUE-SPECIFICATION',
     'SHORT-LABEL VARIATION-POINT VALUE'),
    ('NETWORK-REPRESENTATION-PROPS',
     'SW-DATA-DEF-PROPS-VARIANTS'),
    ('SW-DATA-DEF-PROPS-CONDITIONAL',
     'DISPLAY-PRESENTATION STEP-SIZE SW-VALUE-BLOCK-SIZE-MULTS ANNOTATIONS SW-ADDR-METHOD-REF SW-ALIGNMENT '
     'BASE-TYPE-REF SW-BIT-REPRESENTATION SW-CALIBRATION-ACCESS SW-VALUE-BLOCK-SIZE SW-CALPRM-AXIS-SET '
     'SW-TEXT-PROPS SW-COMPARISON-VARIABLES COMPU-METHOD-REF DATA-CONSTR-REF SW-DATA-DEPENDENCY '
     'DISPLAY-FORMAT IMPLEMENTATION-DATA-TYPE-REF SW-HOST-VARIABLE SW-IMPL-POLICY '
     'ADDITIONAL-NATIVE-TYPE-QUALIFIER SW-INTENDED-RESOLUTION SW-INTERPOLATION-METHOD INVALID-VALUE '
     'MC-FUNCTION SW-IS-VIRTUAL SW-POINTER-TARGET-PROPS SW-RECORD-LAYOUT-REF SW-REFRESH-TIMING UNIT-REF '
     'VALUE-AXIS-DATA-TYPE-REF VARIATION-POINT'),
    ('SYSTEM-SIGNAL',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'VARIATION-POINT DYNAMIC-LENGTH PHYSICAL-PROPS'),
    ('SW-BASE-TYPE',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'BLUEPRINT-POLICYS SHORT-NAME-PATTERN VARIATION-POINT BASE-TYPE-SIZE MAX-BASE-TYPE-SIZE '
     'BASE-TYPE-ENCODING MEM-ALIGNMENT BYTE-ORDER NATIVE-DECLARATION'),
    ('ECU-INSTANCE',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'VARIATION-POINT ASSOCIATED-COM-I-PDU-GROUP-REFS ASSOCIATED-CONSUMED-PROVIDED-SERVICE-INSTANCE-GROUPS '
     'ASSOCIATED-PDUR-I-PDU-GROUP-REFS CAN-TP-ADDRESS-REFS CLIENT-ID-RANGE COM-CONFIGURATION-GW-TIME-BASE '
     'COM-CONFIGURATION-RX-TIME-BASE COM-CONFIGURATION-TX-TIME-BASE COM-ENABLE-MDT-FOR-CYCLIC-TRANSMISSION '
     'COMM-CONTROLLERS CONNECTORS DIAGNOSTIC-ADDRESS DIAGNOSTIC-PROPS DLT-CONFIG DO-IP-CONFIG '
     'ECU-INSTANCE-PROPSS ECU-TASK-PROXY-REFS ETH-SWITCH-PORT-GROUP-DERIVATION PARTITIONS PN-RESET-TIME '
     'PNC-PREPARE-SLEEP-TIMER PNC-SYNCHRONOUS-WAKEUP SLEEP-MODE-SUPPORTED TCP-IP-ICMP-PROPS-REF '
     'TCP-IP-PROPS-REF TP-ADDRESS-REFS V-2-X-SUPPORTED WAKE-UP-OVER-BUS-SUPPORTED'),
    ('CAN-COMMUNICATION-CONTROLLER',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'VARIATION-POINT CAN-COMMUNICATION-CONTROLLER-VARIANTS'),
    ('CAN-COMMUNICATION-CONTROLLER-CONDITIONAL',
     'WAKE-UP-BY-CONTROLLER-SUPPORTED CAN-CONTROLLER-ATTRIBUTES VARIATION-POINT'),
    ('CAN-COMMUNICATION-CONNECTOR',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'COMM-CONTROLLER-REF CREATE-ECU-WAKEUP-SOURCE DYNAMIC-PNC-TO-CHANNEL-MAPPING-ENABLED '
     'ECU-COMM-PORT-INSTANCES PNC-FILTER-ARRAY-MASKS PNC-GATEWAY-TYPE VARIATION-POINT PNC-WAKEUP-CAN-ID '
     'PNC-WAKEUP-CAN-ID-EXTENDED PNC-WAKEUP-CAN-ID-MASK PNC-WAKEUP-DATA-MASK PNC-WAKEUP-DLC'),
    ('ETHERNET-COMMUNICATION-CONNECTOR',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'COMM-CONTROLLER-REF CREATE-ECU-WAKEUP-SOURCE DYNAMIC-PNC-TO-CHANNEL-MAPPING-ENABLED '
     'ECU-COMM-PORT-INSTANCES PNC-FILTER-ARRAY-MASKS PNC-GATEWAY-TYPE VARIATION-POINT '
     'AP-APPLICATION-ENDPOINTS ETH-IP-PROPS-REF IP-V-6-PATH-MTU-ENABLED IP-V-6-PATH-MTU-TIMEOUT '
     'MAXIMUM-TRANSMISSION-UNIT NEIGHBOR-CACHE-SIZE NETWORK-ENDPOINT-REFS PATH-MTU-ENABLED '
     'PATH-MTU-TIMEOUT PNC-FILTER-DATA-MASK UNICAST-NETWORK-ENDPOINT-REF'),
    ('FRAME-PORT',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'COMMUNICATION-DIRECTION VARIATION-POINT'),
    ('I-PDU-PORT',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'COMMUNICATION-DIRECTION VARIATION-POINT I-PDU-SIGNAL-PROCESSING KEY-ID RX-SECURITY-VERIFICATION '
     'TIMESTAMP-RX-ACCEPTANCE-WINDOW USE-AUTH-DATA-FRESHNESS'),
    ('I-SIGNAL-PORT',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'COMMUNICATION-DIRECTION VARIATION-POINT DATA-FILTER FIRST-TIMEOUT HANDLE-INVALID TIMEOUT'),
    ('ETHERNET-CLUSTER',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'VARIATION-POINT ETHERNET-CLUSTER-VARIANTS'),
    ('ETHERNET-CLUSTER-CONDITIONAL',
     'BAUDRATE PHYSICAL-CHANNELS PROTOCOL-NAME PROTOCOL-VERSION SPEED COUPLING-PORT-CONNECTIONS '
     'COUPLING-PORT-STARTUP-ACTIVE-TIME COUPLING-PORT-SWITCHOFF-DELAY MAC-MULTICAST-GROUPS VARIATION-POINT'),
    ('ETHERNET-PHYSICAL-CHANNEL',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'COMM-CONNECTORS FRAME-TRIGGERINGS I-SIGNAL-TRIGGERINGS MANAGED-PHYSICAL-CHANNEL-REFS PDU-TRIGGERINGS '
     'VARIATION-POINT NETWORK-ENDPOINTS SO-AD-CONFIG VLAN'),
    ('NETWORK-ENDPOINT',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'FULLY-QUALIFIED-DOMAIN-NAME INFRASTRUCTURE-SERVICES IP-SEC-CONFIG NETWORK-ENDPOINT-ADDRESSES '
     'PRIORITY'),
    ('IPV-4-CONFIGURATION',
     'ASSIGNMENT-PRIORITY DEFAULT-GATEWAY DNS-SERVER-ADDRESSES IP-ADDRESS-KEEP-BEHAVIOR IPV-4-ADDRESS '
     'IPV-4-ADDRESS-SOURCE NETWORK-MASK TTL'),
    ('SO-AD-CONFIG',
     'CONNECTIONS CONNECTION-BUNDLES LOGIC-ADDRESSS SOCKET-ADDRESSS'),
    ('SOCKET-ADDRESS',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'ALLOWED-I-PV-6-EXT-HEADERS-REF ALLOWED-TCP-OPTIONS-REF APPLICATION-ENDPOINT CONNECTOR-REF '
     'DIFFERENTIATED-SERVICE-FIELD FLOW-LABEL IP-ADDRESS MULTICAST-CONNECTOR-REFS '
     'PATH-MTU-DISCOVERY-ENABLED PDU-COLLECTION-MAX-BUFFER-SIZE PDU-COLLECTION-TIMEOUT PORT-ADDRESS '
     'STATIC-SOCKET-CONNECTIONS UDP-CHECKSUM-HANDLING VARIATION-POINT'),
    ('APPLICATION-ENDPOINT',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'CONSUMED-SERVICE-INSTANCES DISCOVERY-TECHNOLOGY MAX-NUMBER-OF-CONNECTIONS NETWORK-ENDPOINT-REF '
     'PRIORITY PROVIDED-SERVICE-INSTANCES REMOTING-TECHNOLOGY SERIALIZATION-TECHNOLOGY-REF '
     'TLS-CRYPTO-MAPPING-REF TP-CONFIGURATION'),
    ('TP-CONFIGURATION',
     'GENERIC-TP HTTP-TP IEEE-1722-TP RTP-TP TCP-TP UDP-TP'),
    ('TP-CONFIGURATION',
     'TCP-TP UDP-TP'),
    ('UDP-TP',
     'UDP-TP-PORT'),
    ('UDP-TP-PORT',
     'DYNAMICALLY-ASSIGNED PORT-NUMBER'),
    ('TCP-TP',
     'KEEP-ALIVE-INTERVAL KEEP-ALIVE-PROBES-MAX KEEP-ALIVE-TIME KEEP-ALIVES NAGLES-ALGORITHM '
     'RECEIVE-WINDOW-MIN TCP-RETRANSMISSION-TIMEOUT TCP-TP-PORT'),
    ('TCP-TP-PORT',
     'DYNAMICALLY-ASSIGNED PORT-NUMBER'),
    ('STATIC-SOCKET-CONNECTION',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'I-PDU-IDENTIFIERS REMOTE-ADDRESSS TCP-CONNECT-TIMEOUT TCP-ROLE VARIATION-POINT'),
    ('SO-CON-I-PDU-IDENTIFIER-REF-CONDITIONAL',
     'SO-CON-I-PDU-IDENTIFIER-REF VARIATION-POINT'),
    ('SOCKET-ADDRESS-REF-CONDITIONAL',
     'SOCKET-ADDRESS-REF VARIATION-POINT'),
    ('SOCKET-CONNECTION-IPDU-IDENTIFIER-SET',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'VARIATION-POINT I-PDU-IDENTIFIERS'),
    ('SO-CON-I-PDU-IDENTIFIER',
     'SHORT-NAME SHORT-NAME-FRAGMENTS HEADER-ID PDU-COLLECTION-PDU-TIMEOUT PDU-COLLECTION-SEMANTICS '
     'PDU-COLLECTION-TRIGGER PDU-TRIGGERING-REF'),
    ('GATEWAY',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'VARIATION-POINT ECU-REF FRAME-MAPPINGS I-PDU-MAPPINGS SIGNAL-MAPPINGS'),
    ('I-PDU-MAPPING',
     'INTRODUCTION PDU-MAX-LENGTH PDUR-TP-CHUNK-SIZE SOURCE-I-PDU-REF TARGET-I-PDU VARIATION-POINT'),
    ('TARGET-I-PDU',
     'DEFAULT-VALUE TARGET-I-PDU-REF'),
    ('SYSTEM',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'VARIATION-POINT SYSTEM-DOCUMENTATIONS CLIENT-ID-DEFINITION-SET-REFS '
     'CONTAINER-I-PDU-HEADER-BYTE-ORDER ECU-EXTRACT-VERSION FIBEX-ELEMENTS '
     'INTERPOLATION-ROUTINE-MAPPING-SET-REFS J-1939-SHARED-ADDRESS-CLUSTERS MAPPINGS PNC-VECTOR-LENGTH '
     'PNC-VECTOR-OFFSET ROOT-SOFTWARE-COMPOSITIONS SW-CLUSTERS SYSTEM-VERSION'),
    ('FIBEX-ELEMENT-REF-CONDITIONAL',
     'FIBEX-ELEMENT-REF VARIATION-POINT'),
    ('ADMIN-DATA',
     'LANGUAGE USED-LANGUAGES DOC-REVISIONS SDGS'),
    ('SDG',
     'SDG-CAPTION SDG-CAPTION-REF SDX-REF SDXF SD SDG SDF VARIATION-POINT'),
    ('CAN-CONTROLLER-FD-ATTRIBUTES',
     'PADDING-VALUE PROP-SEG SSP-OFFSET SYNC-JUMP-WIDTH TIME-SEG-1 TIME-SEG-2 '
     'TRCV-DELAY-COMPENSATION-OFFSET TX-BIT-RATE-SWITCH'),
    ('VLAN',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'VLAN-IDENTIFIER'),
    ('ETHERNET-COMMUNICATION-CONTROLLER',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'VARIATION-POINT ETHERNET-COMMUNICATION-CONTROLLER-VARIANTS'),
    ('ETHERNET-COMMUNICATION-CONTROLLER-CONDITIONAL',
     'WAKE-UP-BY-CONTROLLER-SUPPORTED COUPLING-PORTS MAC-LAYER-TYPE MAC-UNICAST-ADDRESS '
     'MAXIMUM-RECEIVE-BUFFER-LENGTH MAXIMUM-TRANSMISSION-UNIT MAXIMUM-TRANSMIT-BUFFER-LENGTH '
     'SLAVE-ACT-AS-PASSIVE-COMMUNICATION-SLAVE SLAVE-QUALIFIED-UNEXPECTED-LINK-DOWN-TIME VARIATION-POINT'),
    ('COUPLING-PORT',
     'SHORT-NAME SHORT-NAME-FRAGMENTS LONG-NAME DESC CATEGORY ADMIN-DATA INTRODUCTION ANNOTATIONS '
     'CONNECTION-NEGOTIATION-BEHAVIOR COUPLING-PORT-DETAILS COUPLING-PORT-ROLE COUPLING-PORT-SPEED '
     'DEFAULT-VLAN-REF MAC-LAYER-TYPE MAC-MULTICAST-ADDRESS-REFS PHYSICAL-LAYER-TYPE PLCA-PROPS '
     'PNC-MAPPING-REFS RECEIVE-ACTIVITY VLAN-MEMBERSHIPS VLAN-MODIFIER-REF '
     'WAKEUP-SLEEP-ON-DATALINE-CONFIG-REF VARIATION-POINT'),
    ('VLAN-MEMBERSHIP',
     'DEFAULT-PRIORITY DHCP-ADDRESS-ASSIGNMENT SEND-ACTIVITY VLAN-REF'),
)

ORDER: dict[str, tuple[str, ...]] = {}
for _tag, _seq in _ORDERS:          # a tag listed twice (different contexts) keeps its longest sequence
    if len(_seq.split()) > len(ORDER.get(_tag, ())):
        ORDER[_tag] = tuple(_seq.split())

# element types written by the generator that may carry a UUID attribute (Identifiable in the schema)
IDENTIFIABLE = frozenset((
    "AR-PACKAGE", "CAN-CLUSTER", "CAN-PHYSICAL-CHANNEL", "CAN-COMMUNICATION-CONTROLLER",
    "CAN-COMMUNICATION-CONNECTOR", "FRAME-PORT", "I-PDU-PORT", "CAN-FRAME", "PDU-TO-FRAME-MAPPING",
    "I-SIGNAL-I-PDU", "I-SIGNAL-TO-I-PDU-MAPPING", "I-SIGNAL", "SYSTEM-SIGNAL", "SW-BASE-TYPE",
    "CAN-FRAME-TRIGGERING", "PDU-TRIGGERING", "I-SIGNAL-TRIGGERING", "ETHERNET-CLUSTER",
    "ETHERNET-PHYSICAL-CHANNEL", "VLAN", "NETWORK-ENDPOINT", "ETHERNET-COMMUNICATION-CONTROLLER",
    "COUPLING-PORT", "ETHERNET-COMMUNICATION-CONNECTOR", "SOCKET-ADDRESS", "APPLICATION-ENDPOINT",
    "STATIC-SOCKET-CONNECTION", "SOCKET-CONNECTION-IPDU-IDENTIFIER-SET", "GATEWAY"))

# namespace for deterministic UUIDs: the same AUTOSAR path always gets the same UUID, so
# regenerating a file does not change unrelated identities (DaVinci compares by path anyway)
_UUID_NS = uuid.UUID("5f1d2b8e-7c43-4f0e-9a51-2a1c6b9d4e70")


def stable_uuid(path: str) -> str:
    return uuid.uuid5(_UUID_NS, path).hex


def position(parent_tag: str, child_tag: str, existing: list[str]) -> int | None:
    """Index at which *child_tag* goes among the *existing* child tags (None = append)."""
    order = ORDER.get(parent_tag)
    if not order or child_tag not in order:
        return None
    rank = order.index(child_tag)
    for i, tag in enumerate(existing):
        if tag in order and order.index(tag) > rank:
            return i
    return None


def insert(parent, child):
    """Insert *child* into *parent* at its schema position, keeping the file's indentation."""
    kids = [c for c in parent if isinstance(c.tag, str)]
    idx = position(local(parent), local(child), [local(c) for c in kids])
    return arxml.insert_child(parent, child, idx)


def ensure(parent, tag: str):
    """Return the child *tag* of *parent*, creating it at its schema position when missing."""
    el = parent.find(q(tag))
    if el is None:
        el = insert(parent, E(tag))
    return el


def E(tag: str, *children, text=None, **attrib):
    """Build an element. Children are (re)ordered by schema position; None children are skipped.

    Attribute names use '_' for '-' (``DEST``, ``UUID`` work as they are)."""
    el = arxml.make(tag, None if text is None else str(text),
                    {k.replace("_", "-"): str(v) for k, v in attrib.items()})
    kids = [c for c in children if c is not None]
    order = ORDER.get(tag)
    if order:
        kids.sort(key=lambda c: order.index(local(c)) if local(c) in order else len(order))
    for c in kids:
        el.append(c)
    return el


def T(tag: str, text) -> object:
    """Leaf element with text (None when *text* is None, so it can be passed to E())."""
    if text is None:
        return None
    return arxml.make(tag, str(text))


def R(tag: str, dest: str, path: str):
    """Reference element ``<TAG DEST="...">/path</TAG>``."""
    return arxml.make(tag, path, {"DEST": dest})
